### Recuperar informacion del pokemon ditto
GET http://localhost:3000/pokemon/ditto
### Para crear un pokemon
POST http://localhost:3000/pokemon
Content-Type: application/json

{
    "name": "ditto",
    "type": "normal",
    "moves": [
        "transform"
    ]
}
### Recuperar todas las películas
GET http://localhost:3000/movies
### Recuperar una película por su id
GET http://localhost:3000/movies/aa391090-b938-42eb-b520-86ea0aa3917b
### Recuperar todas las películas por un género
GET http://localhost:3000/movies?genre=Drama
### Crear una película con POST
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}
### Actualizar una película
PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "year": 1998
}
